### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-2-entrevista-reciclaenexus#2]
[Entrevista_Preguntas.pdf](https://github.com/user-attachments/files/16840803/Entrevista_Preguntas.pdf)

**Comment by josealfredo79** [comment]
No se ha calificado..

**Comment by SANDRAVELASCO** [comment]
20/20 Muy bien

**Comment by SANDRAVELASCO** [comment]
Preparación: Antes de la entrevista los integrantes no definieron an bien us preguntas, ni objetivamente, por tanto = 4
Conocimiento ganado: el estudiante ha ganado conocimiento a partir de la entrevista realizada pero le falta profundizar= 4
Informe: Presenta un titulo atractivo y una buena portada , mis mo al que hace referencia al tema y está bien el desarrollo de la entrevista: 5
Redacción: El informe se presenta de manera correcta utilizando coherencia y buena ortografía= 5
Sumatoria de puntos: 4+4+5+5= 18 /20
18/20

**Comment by josealfredo79** [comment]
Revisado...
